### ISSUE TITLE
Scraper authorization code is currently a stub

### ISSUE THREAD

**Issue by jamescowens** [jamescowens/Gridcoin-Research#11]
The IsScraperAuthorized() and IsScraperAuthorizedToBroadcastManifests() are currently stubbed out to true for final development and early testing. These will have to be fleshed out during middle and final testing on testnet before production. Some comments from the code...

// The idea here is that there are two levels of authorization. The first level is whether any
// node can operate as a "scraper", in other words, download the stats files themselves.
// The second level, which is the IsScraperAuthorizedToBroadcastManifests() function,
// is to authorize a particular node to actually be able to publish manifests.
// The second function is intended to override the first, with the first being a network wide
// policy. So to be clear, if the network wide policy has IsScraperAuthorized() set to false
// then ONLY nodes that have IsScraperAuthorizedToBroadcastManifests() can download stats at all.
// If IsScraperAuthorized() is set to true, then you have two levels of operation allowed.
// Nodes can run -scraper and download stats for themselves. They will only be able to publish
// manifests if for that node IsScraperAuthorizedToBroadcastManifests() evaluates to true.
// This allows flexibility in network policy, and will allow us to convert from a scraper based
// approach to convergence back to individual node stats download and convergence without a lot of
// headaches.

I think we need to identify the scraper via a public key to either the default address or a specific addresses/key generated for the purpose of scraper authorization.

For the IsScraperAuthorizedToBroadcastManifests() function, the public keys for the authorized scrapers should be injected into the appcache via signed admin message.

For the IsScraperAuthorized(), a policy value (flag) should be injected into the appcache via signed administrative message to either allow or disallow by network policy individual nodes from downloading stats.

**Comment by jamescowens** [comment]
Also,

Per the discussion on Slack...

I think we have a chicken and egg problem in CScraperManifest::RecvManifest.

CScraperManifest::RecvManifest uses CScraperManifest::UnserializeCheck, which intends to check the authorized scraper list and if so error, which will force a banscore in CScraperManifest::RecvManifest.

My concern is that if the authorized scraper list is kept in the appcache via administrative message, it is possible in a corner case that manifests from that scraper could arrive at a node before the appcache is up to date with the authorization. This is especially true if the node is not in sync.

This could cause a node to ban a scraper unnecessarily.

**Comment by jamescowens** [comment]
Some final comments on this. The receive side checks, which call IsScraperAuthorizedToBroadcastManifests are going to have to be maintained. One of the goals of the security here is to protect against a bad actor (malicious) scraper node that may be publishing manifests without authorization. Therefore we must assume that any send-side rules could be violated by any node.

This means the calls to bool CScraperManifest::IsManifestAuthorized(CPubKey& PubKey) must be maintained in the CScraperManifest::UnserializeCheck(CReaderStream& ss). We must also continue to check periodically during the scraper (or NN) loop during "housekeeping" and delete unauthorized manifests, because we must properly handle the removal of existing manifests by a scraper that gets deauthorized.

Consider that a scraper can be authorized and publish manifests. These manifests will persist in the network for SCRAPER_CMANIFEST_RETENTION_TIME, which is 48 hours. If that scraper is deauthorized by either setting the value of the scraper address key in the AppCache SCRAPER section to false or deleting the key, then the existing manifests must be deleted upon a node's receipt of the AppCache update. This is accomplished through ScraperDeleteUnauthorizedCScraperManifests(), which is called in the scraper or NN loop on a periodic basis.

**Comment by jamescowens** [comment]
I think you are right.

**Comment by jamescowens** [comment]
On forwarding manifests, I assume you are talking about the SendPartTo and SendManifestTo at main.cpp ~6592 to ~6596? So the check goes into those two? Does it destabilize the messaging system to stop the forwarding of messages when a node is not in sync?

**Comment by tomasbrod** [comment]
Part related functions do not need such checks. Parts are only requested for manifest, and that matters. About SendManifestTo, I think the check should rater be done in methods that call SendManifestTo.

**Comment by jamescowens** [comment]
Is it ok to make those methods no-ops if the wallet is not in sync? (I.e. if OutOfSyncByAge() is true, then just return with no action.) I do not want to cause problems with message delivery....

**Comment by tomasbrod** [comment]
If wallet is not synced, then no Inv about Manifest should be sent. The Inv is sent when full manifest is received (to all peers) and when peer connects (to that peer). The sending of manifest Inv is the only part that should depend on result of `OutOfSyncBy*()`.
The second issue is a (pseudo) race condition. Manifest objects should not be sent when they become invalid (deleted by message, expired). They should be deleted from the map immediately, but that is hard to do. So check in SendManifestTo or caller and delete from the map (mutex should be locked when accessing the map).

**Comment by jamescowens** [comment]
Yes. You notice I put locking in on the scraper side. I need to implement the locking on the scraper_net side and protect the CScraperManifest map.

**Comment by jamescowens** [comment]
Note. We need to check for sync condition in SendManifestTo, but we are not going to check for manifest expiration. The trailing edge of the expiration and culling of manifests is handled in the scraper/NN loop as part of housekeeping. I do not want to implement a "delete" manifest message on purpose. This could be used by an errant node as an attack vector to try and extinguish all of the manifests across the network. It is the job of the individual nodes to evaluate manifest expirations and cull accordingly.

Note that across the network manifest deletion can be accomplished by changing the AppCache scraper section entries to false to deauthorize manifests from all scrapers, which within the scraper loop time (default 300 seconds), will cause all manifests to be deleted.

We could implement a special function to do this in one action if you think it is warranted, but I don't think it is.

**Comment by tomasbrod** [comment]
.

**Comment by tomasbrod** [comment]
> by changing the AppCache scraper section entries to false to deauthorize manifests from all scrapers, which within the scraper loop time (default 300 seconds), will cause all manifests to be deleted.
By the time the manifests are deleted in the scraper loop, the manifests, signed by now invalid key, can be advertised and sent to other nodes. All the peers will evaluate the manifest to be invalid (signed by de-authorized key) and eventually ban the sender. I hope you see where the problem is.
If left unattended, any deletion of scraper key would cause great islanding.

**Comment by jamescowens** [comment]
I fixed this problem already I think. Please see

https://github.com/jamescowens/Gridcoin-Research/commit/2437d57fced1db218d6987cb785f460e27e466c0

**Comment by jamescowens** [comment]
Can you think of anything else I need to do there?

**Comment by jamescowens** [comment]
I think pretty much everyone using this branch has upgraded to the latest commit. I currently have five scrapers in the authorization list. Only four are currently acting as scrapers, the other one (the windows node), I have had in NN only mode. I will turn it into a scraper today by passing the scraper flag in and restarting, which will give us five. I will then, once some manifests are published for that one, deauthorize it, and then shut down and restart one of my other nodes to force the request (and send/receive) of the manifest population before the timed culling is likely to occur. I will also ask everyone on testnet to search their debug logs for any occurances of the invalid manifest message to see if there are any issues which would result in unnecessary node banning once SCRAPER_MISBEHAVING_NODE_BANSCORE is set to 50. (That was your original setting before I parameterized it.)

**Comment by tomasbrod** [comment]
This is more tricky issue than I thought it would be. There is still a race condition. `OutOfSync*()` only works when the client is out of sync for longer. Even if it wasn't out of sync, the natural block propagation delay opens a race window too. It is possible to have node A already processed the delete transaction and deleted the manifests, but node B did not yet received the block and will send the deleted manifest.

**Comment by jamescowens** [comment]
I think I have a good answer for this. I will write it out when I get to the office.

**Comment by jamescowens** [comment]
Here is my proposed solution:

If the AppCache authorized scraper list is static we have no issues here. It is only when the scraper list state is changed do we have issues.

I think we can implement a grace period on IsManifestAuthorized and have it not only return a boolean (to indicate the manifest should be deleted), but also in an out parameter the banscore, based on allowing a certain time to pass before exerting a positive banscore on received messages.

Using a 5 min (300 sec) grace period...

So my idea is bool CScraperManifest::IsManifestAuthorized(CPubKey& PubKey, unsigned int& banscore_out);

Let's play this out...

Node A issues addkey delete <address>

Node B has not received block with addkey delete directive...

Node C has already received addkey delete directive.

Node C requests and receives manifests from Node B, including manifests associated with newly unauthorized scraper.

Instead of immediate application of SCRAPER_MISBEHAVING_NODE_BANSCORE, the value of IsManifestAuthorized would be 0, and the banscore_out parameter would be 0 for the grace period. The action would be to delete the manifests but NOT increase the banscore of the sending node for the grace period. Any manifests received unauthorized after the grace period would have a banscore_out of SCRAPER_MISBEHAVING_NODE_BANSCORE.

I think this works. We have to pick a grace period long enough to cover the longest block propagation time from/to all of the nodes. The block spacing itself is probably a good number, so five minutes is very generous.

The calculation of the grace period is tricky. We have to handle two possible conditions. 1. addkey add <address> false, which preserves the key but changes the value to false, and 2. addkey delete <address> which removes the key entirely. For the second case, the latest time of the key is available, so we can directly calculate the grace period from that. For the first, I am not sure. I think we may have to keep another in memory map to hold literally "deleted" keys for the function to calculate the grace period.
We can handle the "startup" situation as having the initial grace period from startup/in-sync.

**Comment by jamescowens** [comment]
Tomas you agree? If so I will start coding it.

**Comment by tomasbrod** [comment]
I agree with the grace period idea. And the details are sound too.
However I feel that this is getting needlessly complicated. What we want the nodes to do is stop spreading manifests that are not valid. The simplest way is to just not save the manifest that is invalid, not ban the sender peer, and prevent further requests for that hash. Not sure.

**Comment by jamescowens** [comment]
I am going to try to implement it anyway. I am concerned that the simple approach, just deleting and not increasing banscore will allow someone to DDOS the network with unwanted/unauthorized messages, and there will be no way to stop it.

**Comment by jamescowens** [comment]
Clarifying my comment... even if we got rid of the banscore requirement and stopped the FORWARDING of bad messages, the issue is that someone taking control of a highly connected node could still cause a lot of problems. I will take a shot at implementing this. I am not afraid of a little complexity as long as the implementation is clear. I think we have done a pretty good job in this code on commenting and making the coding reasonably clear from a maintainability point of view.

**Comment by tomasbrod** [comment]
> someone taking control of a highly connected node could still cause a lot of problems.
I agree.

**Comment by jamescowens** [comment]
I am going to close this, because I think we have addressed everything. Tomas?
